config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, only:[:sessions]
    devise_for :users, only:[:sessions]
    devise_scope :admin do
        authenticated :admin do
            root 'borrows#mypadentries', as: 'admin_root'
            resources :borrows, only: :index
            resources :borrows do
                collection do
                    get 'chargerentries', to: 'borrows#chargerentries', as: 'chargerentries'
                    get 'mypadentries', to: 'borrows#mypadentries', as: 'mypadentries'
                    get 'purge', to: 'borrows#purge', as: 'purge'
                end
             end
        end
    end

    devise_scope :user do
        authenticated :user do
            resources :borrows, only: :index
            root 'borrows#index', as: 'user_root'
            resources :borrows do
                collection do
                    get 'chargerborrows', to: 'borrows#chargerborrows', as: 'chargerborrows'
                end
            end
        end
    end

resources :borrows, only: :index
    resources :borrows do
        collection do
            get ':id/returnpad', to: 'borrows#returnpad', as:'returnpad'
            get ':id/returncharger', to: 'borrows#returncharger', as: 'returncharger'
        end
     end
    
resources :my_pads do
    collection do
        get 'chargepage', to: 'my_pads#chargepage', as: 'chargepage'
        get 'updatepage', to: 'my_pads#updatepage', as: 'updatepage'
        get 'repairpage', to: 'my_pads#repairpage', as: 'repairpage'
        get 'out', to: 'my_pads#out', as: 'out' 
        get ':id/charge', to: 'my_pads#charge', as: 'charge'
        get ':id/update', to: 'my_pads#update', as: 'update'
        get ':id/repair', to: 'my_pads#repair', as: 'repair'
    end
end
    
resources :chargers do
    collection do
        get 'out', to: 'chargers#out', as: 'out'
    end
end

root 'devise/sessions#new'
#root 'publics#home'
end

app/models/my_pad.rb
class MyPad < ActiveRecord::Base
    has_many :borrows
    validates :reference_number, :last_updated, presence: {message: "must be answered."}
    validates_associated :borrows
    
    def to_s
        self.reference_number
    end 
end

app/controllers/my_pads_controller.rb
class MyPadsController < ApplicationController
  def index
    @my_pad = MyPad.all.order('reference_number ASC') 
  end

  def new
    @my_pad = MyPad.new
  end

  def create
    @my_pad = MyPad.new(mypad_params)
      if @my_pad.save
        redirect_to my_pads_path
      else
        render 'my_pads/new'
      end
  end
  
  def edit
     @my_pad = MyPad.find(params[:id])
  end

  def destroy
     @my_pad = MyPad.find(params[:id])
     @my_pad.delete
     redirect_to my_pads_path
  end
  
  def charge
   @my_pad = MyPad.find(params[:id])
    if @my_pad.charging == false
      @my_pad.charging = true
      redirect_to my_pads_path
    else
      @my_pad.charging = false
      redirect_to chargepage_my_pads_path
    end
    @my_pad.save
    
  end
  
  def update
   @my_pad = MyPad.find(params[:id])
    if @my_pad.for_updating == false
      @my_pad.for_updating = true
      redirect_to my_pads_path
    else
      @my_pad.for_updating = false
      @my_pad.last_updated = DateTime.today
      redirect_to updatepage_my_pads_path
    end
    @my_pad.save
    
  end
  
  def repair
   @my_pad = MyPad.find(params[:id])
      if @my_pad.for_repair == false
        @my_pad.for_repair = true
        redirect_to my_pads_path
      else
        @my_pad.for_repair = false
        redirect_to repairpage_my_pads_path
      end
      @my_pad.save
  end 
   
  private
    def mypad_params
      params.require(:my_pad).permit(:reference_number, :last_updated, :status, :charging, :for_repair, :for_updating)
    end
end

app/helpers/my_pads_helper.rb
module MyPadsHelper
end

app/views/my_pads/_form.html.erb
<%= simple_form_for @my_pad do |f| %>
    <%= f.error_notification %>
    <%= f.input :reference_number, :label => "Reference Number", as: "string", required: true %>
    <%= f.input :last_updated, :label => "Last Updated", as: "date", required: true %>
    <%= f.hidden_field :status, :value => true %>
    <%= f.hidden_field :for_repair, :value => false %>
    <%= f.hidden_field :for_updating, :value => false %>
    <%= f.hidden_field :charging, :value => false %>
   
    
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', :back, class: "btn btn-primary" %>
<% end %>

app/views/my_pads/chargepage.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
	    <% @my_pad = MyPad.all.order('reference_number ASC')  %>
		<h1 class="text-center">Charging myPads</h1>
		<h3 class = "text-center">Count: <%= if @my_pad.where(charging: true) != nil then @my_pad.where(charging: true).count else "0" end %> </h2>
	</div>
</div>
<div class="container">
    <table class="table">
    <thead class="thead-dark">
    <tr><th>Reference Number</th><th>Action</th></tr>
    <% @my_pad.each do |p| %>
        <tr>
            <% if p.charging == true %>
                <td><%= p.reference_number %></td>
                <td><%= link_to "Finish Charging", charge_my_pads_path(p), data: {confirm: "myPad will not be set to charging. Are you sure?"}, class: "btn btn-primary"%></td>
            <% end %>
        </tr>
    <% end %>
    </table> 
    <%= link_to 'Back', :back, class: "btn btn-primary" %>
</div>

app/views/my_pads/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1 class="text-center">Edit myPad</h1>
	</div>
</div>
<div class="container">
	<%= render 'my_pads/form' %>	
</div> 

app/views/my_pads/index.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center">In House myPads</h1>
		<h3 class = "text-center">Count: <%= if @my_pad.where(status: true) != nil then @my_pad.where(status: true).count else "0" end %></h2>
	</div>
</div>

<div>
    <div class="container">
    <table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Reference Number</th>
        <th>Last Updated</th>
        <th>Action</th>
        <th>Update</th>
        <th>Repair</th>
        <th>Charging</th>
    </tr>

    <% @my_pad.each do |p| %>
        <tr>
            <% if p.status == true %>
                <td><%= p.reference_number %></td>
                <td><%= p.last_updated.strftime("%B %d, %Y")%></td>
                <td><%= link_to "Delete", my_pad_path(p), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
                <td><%= if p.for_updating == true then "For Updating" else link_to "Update", update_my_pads_path(p), data: {confirm: "myPad will be set to update. Are you sure?"}, class: "btn btn-primary" end %></td>
                <td><%= if p.for_repair == true then "For Repair" else link_to "Repair",repair_my_pads_path(p), data: {confirm: "myPad will be set to repair. Are you sure?"}, class: "btn btn-primary" end  %></td>
                <td><%= if p.charging == true then "Charging" else link_to "Charge", charge_my_pads_path(p), data: {confirm: "myPad will be set to charging. Are you sure?"}, class: "btn btn-primary" end %></td>
           <% end %>
        </tr>
    <% end %>
    </table> 
    <%= link_to "Create New myPad", new_my_pad_path, class: "btn btn-primary" %>
    <br>
    <br>
    <br>
    <br>
</div>
</div>

app/views/my_pads/new.html.erb
<div class="container">
	<div class="page-header">
		<br>
		<br>
		<h1 class="text-center">New myPad</h1>
	</div>
</div>
<div class="container">
	<%= render 'my_pads/form' %>	
</div>

app/views/my_pads/out.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center">Borrowed myPads</h1>
		 <% @my_pad = MyPad.all.order('reference_number ASC')  %>
		<h3 class = "text-center">Count: <%= if @my_pad.where(status: false) != nil then @my_pad.where(status: false).count else "0" end %></h2>
	</div>
</div>


<div class="container">
    <table class="table">
        <thead class="thead-dark">
    <tr><th>Reference Number</th><th>Last Updated</th></tr>
    <% @my_pad.each do |p| %>
        <tr>
            <% if p.status == false %>
                <td><%= p.reference_number %></td>
                <td><%= p.last_updated.strftime("%B %d, %Y") %></td>
            <% else %>
            <% end %>
        </tr>
    <% end %>
    </table> 
     <%= link_to 'Back', :back, class: "btn btn-primary" %>
</div>

app/views/my_pads/repairpage.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center">myPads for Repair</h1>
		 <% @my_pad = MyPad.all.order('reference_number ASC')  %>
		<h3 class = "text-center">Count: <%= if @my_pad.where(for_repair: true) != nil then @my_pad.where(for_repair: true).count else "0" end %></h2>
	</div>
</div>
<div class="container">
    <table class="table">
    <thead class="thead-dark">
    <tr><th>Reference Number</th><th>Action</th></tr>
    <% @my_pad.each do |p| %>
        <tr>
            <% if p.for_repair == true %>
                <td><%= p.reference_number %></td>
                <td><%= link_to "Done with Repair", repair_my_pads_path(p), data: {confirm: "myPad will not be set for repair. Are you sure?"}, class: "btn btn-primary"%></td>
            <% end %>
        </tr>
    <% end %>
    </table> 
     <%= link_to 'Back', :back, class: "btn btn-primary" %>
</div>

app/views/my_pads/updatepage.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center">myPads for Updating</h1>
		 <% @my_pad = MyPad.all.order('reference_number ASC')  %>
		<h3 class = "text-center">Count: <%= if @my_pad.where(for_updating: true) != nil then @my_pad.where(for_updating: true).count else "0" end %></h2>
	</div>
</div>
<div class="container">
    <table class="table">
    <thead class="thead-dark">
    <tr><th>Reference Number</th><th>Action</th></tr>
    <% @my_pad.each do |p| %>
        <tr>
            <% if p.for_updating == true %>
                <td><%= p.reference_number %></td>
                <td><%= link_to "Done with Update", update_my_pads_path(p), data: {confirm: "myPad will not be set for updating. Are you sure?"}, class: "btn btn-primary"%></td>
            <% end %>
        </tr>
    <% end %>
    </table> 
     <%= link_to 'Back', :back, class: "btn btn-primary" %>
</div>