config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, only:[:sessions]
    devise_for :users, only:[:sessions]
    devise_scope :admin do
        authenticated :admin do
            root 'borrows#mypadentries', as: 'admin_root'
            resources :borrows, only: :index
            resources :borrows do
                collection do
                    get 'chargerentries', to: 'borrows#chargerentries', as: 'chargerentries'
                    get 'mypadentries', to: 'borrows#mypadentries', as: 'mypadentries'
                    get 'purge', to: 'borrows#purge', as: 'purge'
                end
             end
        end
    end

    devise_scope :user do
        authenticated :user do
            resources :borrows, only: :index
            root 'borrows#index', as: 'user_root'
            resources :borrows do
                collection do
                    get 'chargerborrows', to: 'borrows#chargerborrows', as: 'chargerborrows'
                end
            end
        end
    end

resources :borrows, only: :index
    resources :borrows do
        collection do
            get ':id/returnpad', to: 'borrows#returnpad', as:'returnpad'
            get ':id/returncharger', to: 'borrows#returncharger', as: 'returncharger'
        end
     end
    
resources :my_pads do
    collection do
        get 'chargepage', to: 'my_pads#chargepage', as: 'chargepage'
        get 'updatepage', to: 'my_pads#updatepage', as: 'updatepage'
        get 'repairpage', to: 'my_pads#repairpage', as: 'repairpage'
        get 'out', to: 'my_pads#out', as: 'out' 
        get ':id/charge', to: 'my_pads#charge', as: 'charge'
        get ':id/update', to: 'my_pads#update', as: 'update'
        get ':id/repair', to: 'my_pads#repair', as: 'repair'
    end
end
    
resources :chargers do
    collection do
        get 'out', to: 'chargers#out', as: 'out'
    end
end

root 'devise/sessions#new'
#root 'publics#home'
end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
    belongs_to :my_pad
    belongs_to :charger
    require 'csv'
    
    validates :name, :flight_number, :id_number, :position, :my_pad_id, :charger_id, :released_by, :charger_expected_return, :my_pad_expected_return, presence: {message: "must be answered" }
   # validates_associated :my_pad, :charger
    
    def self.to_csv(options ={})
        desired_columns = ["id", "name", "position", "flight_number", "date_borrowed", "my_pad_id", "my_pad_actual_return", "charger_id", "charger_actual_return", "released_by"]
        CSV.generate(options) do |csv|
            names = desired_columns << 'my_pad_elapsed_time'
            csv << names
            
            all.each do |borrow|
                if borrow.my_pad_actual_return == nil
                    row = borrow.attributes.values_at(*desired_columns) 
                else
                    elapsed_time = ((borrow.my_pad_actual_return - borrow.date_borrowed)/60).to_f
                    row = borrow.attributes.values_at(*desired_columns) << elapsed_time
                end
                csv << row
            end
        end
    end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
    def index
        @borrow = Borrow.all.order('name ASC') 
        respond_to do |format|
          format.html
          format.csv { send_data @borrow.to_csv, filename: "borrows-#{Date.today}.csv" }
        end
    end

  def new
    @borrow = Borrow.new
  end

  def create
    @borrow = Borrow.new(borrow_params)
    if @borrow.save
        
        #mypad
        @borrow.my_pad.status = false
        @borrow.my_pad.save
        
        #charger
        if @borrow.charger.to_s != "No Charger"
          @borrow.charger.status = false
          @borrow.charger.save
        else
          @borrow.charger.save
        end
      redirect_to borrows_path
    else
      render 'borrows/new'
    end
  end

  def edit
     @borrow = Borrow.find(params[:id])
  end

  def destroy
     @borrow = Borrow.find(params[:id])
     @borrow.delete
     redirect_to mypadentries_borrows_path
  end
  
  def returnpad
    @borrow = Borrow.find(params[:id])
    @borrow.my_pad_actual_return = DateTime.now
    @my_pad = MyPad.all
      @my_pad.each do |a|
        if @borrow.my_pad == a
             a.status = true
             a.save
             redirect_to borrows_path
        end
      end
    @borrow.save
  end
  
  def purge
    @borrow = Borrow.all
    @borrow.each do |a|
      a.destroy
    end
    redirect_to mypadentries_borrows_path
  end
  
  def returncharger
    @borrow = Borrow.find(params[:id])
    @borrow.charger_actual_return = DateTime.now
    @charger = Charger.all
      @charger.each do |a|
        if @borrow.charger == a
             a.status = true
             a.save
             redirect_to chargerborrows_borrows_path
        end
      end
    @borrow.save
  end
  
  private
    def borrow_params
      params.require(:borrow).permit!
    end
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/views/borrows/_form.html.erb
<%= simple_form_for @borrow do |f| %>
    <%= f.error_notification %>
    <%= f.input :name, :label => "Full Name", as: "string", required: true %>
    <%= f.input :position, :label => "Position", collection: ['Flight Steward', 'Flight Attendant', 'Admin', 'Trainer'], prompt: "Select a Position", required: true %>
    <%= f.input :id_number, :label => "ID Number", as: "integer", required: true %>
    <%= f.input :flight_number, :label => "Flight Number",as: "string", required: true %>
   
    <%= f.association :my_pad, collection: MyPad.where(status: true, for_repair: false, for_updating: false, charging: false).order('reference_number ASC'), :label => "myPad Reference Number", prompt: "Select a myPad", required: true %>
    <%= f.input :my_pad_expected_return, :label => "Expected myPad Return Date", as: "date", required: true, html5: true %>
    
    <%= f.association :charger, collection: Charger.where(status: true).order('reference_number ASC'), :label => "Charger Reference Number", prompt: "Select a Charger", required: true %>
    <%= f.input :charger_expected_return, :label => "Expected Charger Return Date", as: "date", required: true, html5: true%>

    <%= f.hidden_field :date_borrowed, :value => DateTime.now %>
    <%= f.hidden_field :my_pad_actual_return, :value => nil %>
    <%= f.hidden_field :charger_actual_return, :value => nil %>
    
    <%= f.input :released_by, :label => "Released by:", as: "string", required: true %>
   
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', :back, class: "btn btn-primary" %>
<% end %>

app/views/borrows/chargerborrows.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center">Charger Borrow Entries</h1>
	</div>
	
</div>
    <div class="container-fluid">
    <table class="table">
        <thead class="thead-dark">
    <tr><th>Name</th><th>Position</th><th>ID Number</th><th>Flight Number</th><th>Charger Reference Number</th><th>Released by</th><th>Date Borrowed</th><th>Expected Return Date</th><th>Date Returned</th><th></th><th></th></tr>
    <% @borrow = Borrow.all.order('name ASC') %>
    <% @borrow.each do |a| %>
        <tr>
            <% if a.charger.reference_number != "No Charger" %>
                <td><%= a.name %></td>
                <td><%= a.position %></td>
                <td><%= a.id_number %></td>
                <td><%= a.flight_number %></td>
                <td><%= a.charger %></td>
                <td><%= a.released_by %></td>
                <td><%= a.date_borrowed.strftime("%B %d, %Y")  %></td>
                <td><%= a.charger_expected_return.strftime("%B %d, %Y")  %></td>
                
                <td><%= if a.charger_actual_return == nil then "-" else a.charger_actual_return.strftime("%B %d, %Y")  end %></td>
                <td><%= if a.charger_actual_return == nil then link_to "Return", returncharger_borrows_path(a), data: {confirm: "Charger will be returned. Are you sure?"}, class: "btn btn-primary" else " " end %></td></td>
            <%end%>
        </tr>
    <% end %>
    </table> 
    <%= if @borrow.size != 0 then link_to "Delete All Entries", purge_borrows_path, data: {confirm: "Are you sure?"}, class: "btn btn-danger" end %>
    <br>
    <br>
    <br>
    </div>
</div>
</div>

app/views/borrows/chargerentries.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center">Charger Borrow Entries</h1>
	</div>
	
</div>
    <div class="container-fluid">
    <table class="table">
        <thead class="thead-dark">
    <tr><th>Name</th><th>Position</th><th>ID Number</th><th>Flight Number</th><th>Charger Reference Number</th><th>Released by</th><th>Date Borrowed</th><th>Expected Return Date</th><th>Date Returned</th><th></th><th></th></tr>
    <% @borrow = Borrow.all.order('name ASC') %>
    <% @borrow.each do |a| %>
        <tr>
            <% if a.charger.reference_number != "No Charger" %>
                <td><%= a.name %></td>
                <td><%= a.position %></td>
                <td><%= a.id_number %></td>
                <td><%= a.flight_number %></td>
                <td><%= a.charger %></td>
                <td><%= a.released_by %></td>
                <td><%= a.date_borrowed.strftime("%B %d, %Y")  %></td>
                <td><%= a.charger_expected_return.strftime("%B %d, %Y")  %></td>
                <td><%= if a.charger_actual_return == nil then "-" else a.charger_actual_return.strftime("%B %d, %Y")  end %></td>
                <td><%= link_to "Delete", borrow_path(a), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
            <%end%>
        </tr>
    <% end %>
    </table> 
    <%=  if @borrow.size != 0 then link_to "Export to CSV", borrows_path(format: 'csv'), class: "btn btn-primary" end %>
    <br>
    <br>
    <%= if @borrow.size != 0 then link_to "Delete All Entries", purge_borrows_path, data: {confirm: "Are you sure?"}, class: "btn btn-danger" end %>
    <br>
    <br>
    <br>
    </div>
</div>
</div>

app/views/borrows/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1 class="text-center">Edit Borrow Entry</h1>
	</div>
</div>
<div class="container">
	<%= render 'borrows/form' %>	
</div>

app/views/borrows/index.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center"> myPad Borrow Entries</h1>
	</div>
	
</div>
    <div class="container-fluid">
    <table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Name</th>
        <th>Position</th>
        <th>ID Number</th>
        <th>Flight Number</th>
        <th>myPad Reference Number</th>
        <th>Released by</th>
        <th>Date Borrowed</th>
        <th>Expected Return Date</th>
        <th>Date Returned</th>
        <th></th>
        <th></th>
    </tr>
    <% @borrow.each do |a| %>
        <tr>
            <td><%= a.name %></td>
            <td><%= a.position.to_str %></td>
            <td><%= a.id_number %></td>
            <td><%= a.flight_number %></td>
            <td><%= a.my_pad %></td>
            <td><%= a.released_by %></td>
            <td><%= a.date_borrowed.strftime("%B %d, %Y")  %></td>
            <td><%= a.my_pad_expected_return.strftime("%B %d, %Y")  %></td>
            
            <td><%= if a.my_pad_actual_return == nil then "-" else a.my_pad_actual_return.strftime("%B %d, %Y")  end %></td>
            <td><%= if a.my_pad_actual_return == nil then link_to "Return", returnpad_borrows_path(a), data: {confirm: "myPad will be returned. Are you sure?"}, class: "btn btn-primary" else " " end %></td></td>
        </tr>
    <% end %>
    </table> 
    <%= link_to "Borrow a myPad", new_borrow_path, class: "btn btn-primary" %>
    <br>
    <br>
    </div>
</div>
</div>

app/views/borrows/mypadentries.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center"> myPad Borrow Entries</h1>
	</div>
	
</div>
    <div class="container-fluid">
    <table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Name</th>
        <th>Position</th>
        <th>ID Number</th>
        <th>Flight Number</th>
        <th>myPad Reference Number</th>
        <th>Released by</th>
        <th>Date Borrowed</th>
        <th>Expected Return Date</th>
        <th>Date Returned</th>
        <th></th>
        <th></th>
    </tr>
    <% @borrow = Borrow.all.order('name ASC') %>
    <% @borrow.each do |a| %>
        <tr>
            <td><%= a.name %></td>
            <td><%= a.position.to_str %></td>
            <td><%= a.id_number %></td>
            <td><%= a.flight_number %></td>
            <td><%= a.my_pad %></td>
            <td><%= a.released_by %></td>
            <td><%= a.date_borrowed.strftime("%B %d, %Y")  %></td>
            <td><%= a.my_pad_expected_return.strftime("%B %d, %Y")  %></td>
            
            <td><%= if a.my_pad_actual_return == nil then "-" else a.my_pad_actual_return.strftime("%B %d, %Y")  end %></td>
            <td><%= link_to "Delete", borrow_path(a), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
            
        </tr>
    <% end %>
    </table> 
    <%=  if @borrow.size != 0 then link_to "Export to CSV", borrows_path(format: 'csv'), class: "btn btn-primary" end %>
    <br>
    <br>
    <%= if @borrow.size != 0 then link_to "Delete All Entries", purge_borrows_path, data: {confirm: "Are you sure?"}, class: "btn btn-danger" end %>
    <br>
    <br>
    <br>
    </div>
</div>
</div>

app/views/borrows/new.html.erb
<div class="container">
	<div class="page-header">
		<br>
		<br>
		<h1 class="text-center">Borrow a myPad</h1>
	</div>
</div>
<div class="container">
	<%= render 'borrows/form' %>	
</div>