config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, only:[:sessions]
    devise_for :users, only:[:sessions]
    devise_scope :admin do
        authenticated :admin do
            root 'borrows#mypadentries', as: 'admin_root'
            resources :borrows, only: :index
            resources :borrows do
                collection do
                    get 'chargerentries', to: 'borrows#chargerentries', as: 'chargerentries'
                    get 'mypadentries', to: 'borrows#mypadentries', as: 'mypadentries'
                    get 'purge', to: 'borrows#purge', as: 'purge'
                end
             end
        end
    end

    devise_scope :user do
        authenticated :user do
            resources :borrows, only: :index
            root 'borrows#index', as: 'user_root'
            resources :borrows do
                collection do
                    get 'chargerborrows', to: 'borrows#chargerborrows', as: 'chargerborrows'
                end
            end
        end
    end

resources :borrows, only: :index
    resources :borrows do
        collection do
            get ':id/returnpad', to: 'borrows#returnpad', as:'returnpad'
            get ':id/returncharger', to: 'borrows#returncharger', as: 'returncharger'
        end
     end
    
resources :my_pads do
    collection do
        get 'chargepage', to: 'my_pads#chargepage', as: 'chargepage'
        get 'updatepage', to: 'my_pads#updatepage', as: 'updatepage'
        get 'repairpage', to: 'my_pads#repairpage', as: 'repairpage'
        get 'out', to: 'my_pads#out', as: 'out' 
        get ':id/charge', to: 'my_pads#charge', as: 'charge'
        get ':id/update', to: 'my_pads#update', as: 'update'
        get ':id/repair', to: 'my_pads#repair', as: 'repair'
    end
end
    
resources :chargers do
    collection do
        get 'out', to: 'chargers#out', as: 'out'
    end
end

root 'devise/sessions#new'
#root 'publics#home'
end

app/models/charger.rb
class Charger < ActiveRecord::Base
    has_many :borrows
    validates :reference_number, presence: {message: "must be answered."}
    validates_associated :borrows
    
    def to_s
        self.reference_number
    end 
end

app/controllers/chargers_controller.rb
class ChargersController < ApplicationController
  def index
    @charger = Charger.all.order('reference_number ASC') 
  end

  def new
    @charger = Charger.new
  end
  
  def create
    @charger = Charger.new(charger_params)
      if @charger.save
        redirect_to chargers_path
      else
        render 'chargers/new'
      end
  end
  
  def edit
    @charger = Charger.find(params[:id])
  end

  def destroy
    @charger = Charger.find(params[:id])
    @charger.delete
    redirect_to chargers_path
  end
  
  private
    def charger_params
      params.require(:charger).permit(:reference_number, :status)
    end
end

app/helpers/chargers_helper.rb
module ChargersHelper
end

app/views/chargers/_form.html.erb
<%= simple_form_for @charger do |f| %>
    <%= f.error_notification %>
    <%= f.input :reference_number, :label=> "Reference Number", as: "string", required: true %>
    <%= f.hidden_field :status, :value => true %>
    
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', :back, class: "btn btn-primary" %>
<% end %>

app/views/chargers/index.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center">In House Chargers</h1>
		<h3 class = "text-center">Count: <%= if @charger.all != nil then (@charger.where(status: true).size - 1) else "0" end %></h2>
	</div>
</div>

<div>
    <div class="container">
    <table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Charger Name</th>
        <th>Action</th>
    </tr>
    <% @charger.each do |p| %>
        <tr>
            <% if p.status == true %>
                <% if p.reference_number != "No Charger" %>
                    <td><%= p.reference_number %></td>
                    <td><%= link_to "Delete", charger_path(p), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
                <% end %>
            <% end %>
        </tr>
    <% end %>
    </table> 
    <%= link_to "Create New Charger", new_charger_path, class: "btn btn-primary" %>
    <br>
    <br>
    <br>
    <br>
</div>
</div>

app/views/chargers/new.html.erb
<div class="container">
	<div class="page-header">
		<br>
		<br>
		<h1 class="text-center">Create a Charger</h1>
	</div>
</div>
<div class="container">
	<%= render 'chargers/form' %>	
</div>

app/views/chargers/out.html.erb
<div class="container">
	<div class="page-header">
	    <br>
	    <br>
		<h1 class="text-center">Borrowed Chargers</h1>
		<% @charger = Charger.all.order('reference_number ASC')  %>
		<h3 class = "text-center">Count: <%= if @charger.all != nil then (@charger.where(status: false).size) else "0" end %></h2>
	</div>
</div>

<div>
    <div class="container">
    <table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Charger Name</th>
        <th>Action</th>
    </tr>
    <% @charger.each do |p| %>
        <tr>
            <% if p.status == false %>
                <% if p.reference_number != "No Charger" %>
                    <td><%= p.reference_number %></td>
                    <td><%= link_to "Delete", charger_path(p), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
                <% end %>
            <% end %>
        </tr>
    <% end %>
    </table> 
    <%= link_to "Create New Charger", new_charger_path, class: "btn btn-primary" %>
    <br>
    <br>
    <br>
    <br>
</div>
</div>