config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, only:[:sessions]
    devise_for :users, only:[:sessions]
    devise_scope :admin do
        authenticated :admin do
            root 'borrows#mypadentries', as: 'admin_root'
            resources :borrows, only: :index
            resources :borrows do
                collection do
                    get 'chargerentries', to: 'borrows#chargerentries', as: 'chargerentries'
                    get 'mypadentries', to: 'borrows#mypadentries', as: 'mypadentries'
                    get 'purge', to: 'borrows#purge', as: 'purge'
                end
             end
        end
    end

    devise_scope :user do
        authenticated :user do
            resources :borrows, only: :index
            root 'borrows#index', as: 'user_root'
            resources :borrows do
                collection do
                    get 'chargerborrows', to: 'borrows#chargerborrows', as: 'chargerborrows'
                end
            end
        end
    end

resources :borrows, only: :index
    resources :borrows do
        collection do
            get ':id/returnpad', to: 'borrows#returnpad', as:'returnpad'
            get ':id/returncharger', to: 'borrows#returncharger', as: 'returncharger'
        end
     end
    
resources :my_pads do
    collection do
        get 'chargepage', to: 'my_pads#chargepage', as: 'chargepage'
        get 'updatepage', to: 'my_pads#updatepage', as: 'updatepage'
        get 'repairpage', to: 'my_pads#repairpage', as: 'repairpage'
        get 'out', to: 'my_pads#out', as: 'out' 
        get ':id/charge', to: 'my_pads#charge', as: 'charge'
        get ':id/update', to: 'my_pads#update', as: 'update'
        get ':id/repair', to: 'my_pads#repair', as: 'repair'
    end
end
    
resources :chargers do
    collection do
        get 'out', to: 'chargers#out', as: 'out'
    end
end

root 'devise/sessions#new'
#root 'publics#home'
end

app/views/layouts/_navbar.html.erb
<!-- Latest compiled and minified JavaScript -->
<style>
  .nav.navbar-nav li a:hover {
    background-color: #00897b;
  }
  .nav.navbar-nav li a {
    color: white;
  }
  .navbar-nav > li > .dropdown-menu { 
    background-color: #80cbc4; 
  }
</style>


<!-- Actual Navbar Code -->
<div class="nav navbar-light navbar-fixed-top" style="background-color: #80cbc4">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
  			<span class="sr-only">Toggle Navigation</span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
			</button>
        <a href="/" class="navbar-brand" style= "color: white">myPad Inventory</a>
        
		</div> 
		
		<p class="navbar-text pull-right" style= "color: white">
            <% if admin_signed_in? %> 
                Logged in as <strong><%= current_admin.email %></strong>.
                <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
            <% elsif user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% end %>
        </p>
        
		<div class="collapse navbar-collapse" id="navbarCollapse">
		<ul class="nav navbar-nav">
		<% if admin_signed_in? %>
    		<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">myPads<b class="caret"></b></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><%= link_to "View In House myPads", my_pads_path%></a></li>
                    <li><a href="#"><%= link_to "View Borrowed myPads", out_my_pads_path%></a></li>
                    <li><a href="#"><%= link_to "View Charging myPads", chargepage_my_pads_path %></a></li>
                    <li><a href="#"><%= link_to "View myPads for Updating", updatepage_my_pads_path %></a></li>
                    <li><a href="#"><%= link_to "View myPads for Repair", repairpage_my_pads_path %></a></li>
                    <li><a href="#"><%= link_to "Create a new myPad", new_my_pad_path %></a></li>
                </ul>
            </li>
        
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Chargers<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><%= link_to "Create a new Charger", new_charger_path %></a></li>
                    <li><a href="#"><%= link_to "View Chargers", chargers_path%></a></li>
                    <li><a href="#"><%= link_to "View Borrowed Chargers", out_chargers_path%></a></li>
                </ul>
            </li>
        
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" font-color='#80cbc4'>Borrows<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><%= link_to "View myPad Borrows", mypadentries_borrows_path%></a></li>
                    <li><a href="#"><%= link_to "View Charger Borrows", chargerentries_borrows_path%></a></li>
                </ul>
            </li>
            
        <% elsif user_signed_in? %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">myPads<b class="caret"></b></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><%= link_to "View In House myPads", my_pads_path%></a></li>
                    <li><a href="#"><%= link_to "View Borrowed myPads", out_my_pads_path%></a></li>
                    <li><a href="#"><%= link_to "View Charging myPads", chargepage_my_pads_path %></a></li>
                    <li><a href="#"><%= link_to "View myPads for Updating", updatepage_my_pads_path %></a></li>
                    <li><a href="#"><%= link_to "View myPads for Repair", repairpage_my_pads_path %></a></li>
                    <li><a href="#"><%= link_to "Create a new myPad", new_my_pad_path %></a></li>
                </ul>
            </li>
        
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Chargers<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><%= link_to "Create a new Charger", new_charger_path %></a></li>
                    <li><a href="#"><%= link_to "View In House Chargers", chargers_path%></a></li>
                    <li><a href="#"><%= link_to "View Borrowed Chargers", out_chargers_path%></a></li>
                </ul>
            </li>
         
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Borrows<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><%= link_to "Borrow a myPad", new_borrow_path %></a></li>
                    <li><a href="#"><%= link_to "View myPad Borrows", borrows_path%></a></li>
                    <li><a href="#"><%= link_to "View Charger Borrows", chargerborrows_borrows_path%></a></li>
                </ul>
            </li>
        <% else %>
            <li><a href="#" style="padding:0px"><%= link_to "Log In As Admin", new_admin_session_path %></a></li>
            <li><a href="#" style="padding:0px"><%= link_to "Log In As User", new_user_session_path %></a></li>
        <% end %>
        </ul> 
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myPad Inventory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body style="padding:-4px">

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>